name: Upload CSVs to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp-sa-key }}

      # Step 3: Setup gcloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 4: Upload ALL CSV files automatically
      - name: Upload CSV files to GCS
        run: |
          gsutil cp sample-data/*.csv gs://sales-data-bucket-saurabh/
