name: Upload CSVs to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp_sa_key }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug files (check CSV exists)
        run: ls -R

      - name: Upload CSV to GCS
        run: |
          gsutil cp sample-data/sales2.csv gs://sales-data-bucket-saurabh/